version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/nim/Dockerfile
    tty: true
    environment:
      TZ: Asia/Tokyo
    ports:
      - 9001:5000
    volumes:
      - ./src/server:/root/project
